export const data = {
  id: 0,
  title: 'Ontdek Qualogy',
  sub: '',
  content: `\n  \n  ###### **Bij Qualogy ontwikkelen we samen met onze klanten slimme oplossingen die ervoor zorgen dat zij snel en efficiënt kunnen werken.**\n  \n  Van idee en implementatie tot gebruik en beheer. We gebruiken hiervoor standaard software en bewezen technologieën.\n  \n  \n  Al ontdekken we ook graag nieuwe werelden.\n  Door met lef en creativiteit naar complexe vraagstukken te kijken, komen we tot de beste oplossingen.\n  \n`,
  employee: {
    reversed: false,
    button: null,
    content: null,
    image: {
      id: 0,
      name: '',
      caption: '',
      width: 0,
      height: 0,
      url: 'handshake-banner.png',
      alternativeText: '',
      hash: '',
      ext: '',
      mime: '',
      formats: null,
      size: 0,
    },
  },
  button: {
    id: 0,
    icon: 'arrowRight',
    target: '_self',
    link: '',
    label: 'Lees meer',
  },
};
